name: first-time-setup
run-name: first time setup of repo

on:
  # run when called from another workflow
  workflow_call:

  # run if user manually requests it
  workflow_dispatch:

jobs:
  first-time-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Print contexts
        uses: crazy-max/ghaction-dump-context@v1

      - name: Create Pages branch
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "gh-pages"

      - name: Checkout Pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Clear Pages branch
        run: rm -rf * .github .gitignore

      - name: Make .nojekyll file
        run: touch .nojekyll

      - name: Make placeholder homepage
        run: echo "Your site will appear here" > index.html

      - name: Commit changes to Pages branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          commit_message: "Clear branch"

      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Remove unneeded files
        run: |
          rm -rf \
            README.md \
            demo.md \
            testbed.md \
            .github/ISSUE_TEMPLATE \
            .github/workflows/update-version.yaml \
            .github/pull_request_template.md \

      - name: Rename files
        run: |
          mv .github/user_pull_request_template.md .github/pull_request_template.md

      - name: Set vars for personalization
        run: |
          name="${{ github.repository_owner }}"
          title="${name^}'s Website"
          description="An engaging 1-3 sentence description of your lab."
          echo "NAME=${name}" >> $GITHUB_ENV
          echo "TITLE=${title}" >> $GITHUB_ENV
          echo "DESCRIPTION=${description}" >> $GITHUB_ENV

      - name: Personalize readme for user
        run: |
          echo "
          # ${{ env.TITLE }}

          Visit **[website url](#)** 🚀

          _Built with [Lab Website Template](https://greene-lab.gitbook.io/lab-website-template-docs)_
          " > README.md

      - name: Personalize Jekyll config for user
        uses: actions/github-script@v6
        with:
          script: |
            const { readFileSync, writeFileSync } = require("fs");
            const file = "_config.yaml";
            let contents = readFileSync(file).toString();
            contents = contents
              .replaceAll(/(title):.*/g, "$1: ${{ env.TITLE }}")
              .replaceAll(/(description):.*/g, "$1: ${{ env.DESCRIPTION }}")
              .replaceAll(/(email):.*/g, "$1: contact@${{ env.NAME }}.com")
              .replaceAll(/(github|twitter|instagram|youtube):.*/g, "$1: ${{ env.NAME }}");
            writeFileSync(file, contents);

      - name: Personalize homepage for user
        uses: actions/github-script@v6
        with:
          script: |
            const { readFileSync, writeFileSync } = require("fs");
            const file = "index.md";
            let contents = readFileSync(file).toString();
            const find = /\# Lab Website Template[\s\S]+?({% include section\.html)/g;
            const replace = `# ${{ env.TITLE }}\n\n${{ env.DESCRIPTION }}\n\n$1`;
            contents = contents.replaceAll(find, replace);
            writeFileSync(file, contents);

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Setup repo"
