name: on-pull-request
run-name: on pull request activity

permissions: write-all

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  update-citations:
    uses: ./.github/workflows/update-citations.yaml
  build-preview:
    needs: update-citations
    uses: ./.github/workflows/build-preview.yaml
