name: on-pages
run-name: on pages deploy

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
    branches:
      - gh-pages

jobs:
  update-url:
    # only run on user instance of template, not template itself
    if: github.repository != 'vincerubinetti/lab-website-template'
    uses: ./.github/workflows/update-url.yaml
  build-site:
    needs: update-url
    if: needs.update-url.outputs.changed == 'true'
    uses: ./.github/workflows/build-site.yaml
