name: on-schedule
run-name: on schedule

on:
  schedule:
    # weekly
    - cron: "0 0 * * 1"

  # run if user manually requests it
  workflow_dispatch:

jobs:
  update-citations:
    # only run on user instance of template, not template itself
    if: github.repository != 'vincerubinetti/lab-website-template'
    uses: ./.github/workflows/update-citations.yaml
  build-site:
    needs: update-citations
    if: needs.update-citations.outputs.changed == 'true'
    uses: ./.github/workflows/build-site.yaml
